## When enabling, we need to have proper metrics to decide on autoscaling
autoscaling:
  enabled: false

config:
  display_text: 'Hello World'

# These secrets should come from a vault
secret:
  dbpassword: asecret

dnsPolicy: ClusterFirst

image:
  repository: ghcr.io/mariovw-deriv
  name: helloworld
  pullPolicy: IfNotPresent
  tag: "master"

imagePullSecrets: []

ingress:
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /ping
    alb.ingress.kubernetes.io/group.name: ops-alb-ext
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/target-type: ip
    kubernetes.io/ingress.class: alb
  enabled: false
  host: null

livenessProbe:
  failureThreshold: 6
  httpGet:
    path: /ping
    port: http
    scheme: HTTP
  periodSeconds: 10

readinessProbe:
  failureThreshold: 6
  httpGet:
    path: /ping
    port: http
    scheme: HTTP
  periodSeconds: 5
  successThreshold: 1
  timeoutSeconds: 1

startupProbe:
 failureThreshold: 40
 periodSeconds: 3
 httpGet:
   path: /ping
   port: http
   scheme: HTTP

restartPolicy: Always

replicaCount: 1

nameOverride: ""

fullnameOverride: ""

resources: {}
  # limits:
  #   cpu: 500m
  #   memory: 512Mi
  # requests:
  #   cpu: 100m
  #   memory: 256Mi

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  capabilities:
    drop:
      - all

service:
  type: ClusterIP
  port: 80

nodeSelector: {}

tolerations: []

affinity: {}
