on:
  push:
    branches:
      - master

jobs:
  build-publish-docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/mariovw-deriv/helloworld

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  helm-deployment:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3
      - name: 'Deploy'
        uses: 'deliverybot/helm@v1'
        with:
          release: 'helloworld'
          namespace: 'dev'
          chart: 'app'
          token: '${{ github.token }}'
          values: |
            name: foobar
        env:
          KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'
